app/models/chat_user.py
from .db import Base, db

class ChatUser(Base):
    __tablename__ = "chat_users"

    name = db.Column(db.String(20), nullable=False)
    age = db.Column(db.String(20), nullable=False)
    looking_age = db.Column(db.String(20), nullable=False)
    gender = db.Column(db.String(30), nullable=False)
    looking_gender = db.Column(db.String(30), nullable=False)
    sid = db.Column(db.String(50), nullable=False, unique=True)
    message_to = db.Column(db.String(50), nullable=True, unique=True)    
    status = db.Column(db.String(20), nullable=False, default="free")

    def __repr__(self) -> str:
        return f"<ChatUser>"

app/models/db.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()


class Base(db.Model):
    __abstract__ = True
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

from .chat_user import ChatUser

app/__init__.py
from flask import Flask
from flask_migrate import Migrate

import mimetypes
mimetypes.add_type("application/javascript", ".js")

from .config import APP_CONFIG

migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.update(APP_CONFIG)
    
    app.static_folder = APP_CONFIG["STATIC_FOLDER"]

    from .socketio import socketio
    from .models.db import db

    socketio.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    from .views.message import message
    from .views.home import home

    for blueprint in [message, home]:
        app.register_blueprint(blueprint)

    return app

app/views/home.py
from flask import Blueprint, request, session, redirect, url_for
from datetime import datetime, timezone
from ..functions import render

home = Blueprint("Home", __name__)

@home.route("/")
def index():
    return render(
        "home/index.html",
    )

@home.route("/", methods=["POST"])
def index_post():
    name = request.form.get("m-name")
    age = request.form.get("m-age")
    looking_age = request.form.get("m-looking-age")
    gender = request.form.get("m-gender")
    looking_gender = request.form.get("m-looking-gender")

    if name is None or name == "" or name.strip() == "":
        name = "stranger"
    
    if age is None or age == "" or age == "unknown" or age not in ("unknown", "13-17", "18-30", "31-40", "41-50", "51+"):
        age = "unknown"
    
    if looking_age is None or looking_age == "" or looking_age == "unknown" or looking_age not in ("unknown", "13-17", "18-30", "31-40", "41-50", "51+"):
        looking_age = "unknown"
    
    if gender is None or gender not in ("unknown", "male", "female"):
        gender = "unknown"
    
    if looking_gender is None or looking_gender not in ("unknown", "male", "female"):
        looking_gender = "unknown"
    
    session["chat-name"] = name
    session["chat-age"] = age
    session["chat-looking-age"] = looking_age
    session["chat-gender"] = gender
    session["chat-looking-gender"] = looking_gender
    session["timestat"] = datetime.now(timezone.utc)
    return redirect(url_for("Message.index"))


@home.route("/about")
def about():
    return render(
        "home/about.html",
        title="About"
    )


@home.route("/terms")
def terms():
    return render(
        "home/terms.html",
        title="Terms"
    )

app/views/message.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from datetime import timedelta, datetime, timezone
from sqlalchemy import func
from flask_socketio import emit

from ..socketio import socketio
from ..models.db import db
from ..models.chat_user import ChatUser


message = Blueprint("Message", __name__, url_prefix="/message")


@message.route("/")
def index():
    if session.get("timestat") is None or (datetime.now(timezone.utc) - session["timestat"]) > timedelta(hours=1):
        return redirect(url_for('Home.index'))

    return render_template(
        "message/index.html",
        live_users_count = ChatUser.query.with_entities(func.count(ChatUser.id)).first()[0]
    )


@socketio.on("connect")
def on_connect():
    current_user_sid = request.sid

    user = ChatUser(
        name=session["chat-name"],
        age=session["chat-age"],
        looking_age=session["chat-looking-age"],
        gender=session["chat-gender"],
        looking_gender=session["chat-looking-gender"],
        sid=current_user_sid,
        message_to=None,
        status="free"
    )
    db.session.add(user)
    db.session.commit()

    free_user = ChatUser.query.filter(
        ChatUser.status == "free",
        ChatUser.sid != current_user_sid,
        ChatUser.age == session["chat-looking-age"],
        ChatUser.gender == session["chat-looking-gender"]
    ).first()

    if free_user is None:
        free_user = ChatUser.query.filter(
            ChatUser.status == "free",
            ChatUser.sid != current_user_sid,
            ChatUser.looking_age == session["chat-age"],
            ChatUser.looking_gender == session["chat-gender"]
        ).first()

    if free_user is not None:
        user.message_to = free_user.sid
        user.status = "busy"
        free_user.message_to = current_user_sid
        free_user.status = "busy"
        db.session.commit()

        emit("join-user",{
            "status": "found"
        }, broadcast=False, to=current_user_sid)

        emit("status-message", {
                "message": "You're connected to a stranger!",
                "mimetype": "text"
            }, broadcast=False, to=current_user_sid)

        emit("new-message", {
            "data": f"Hello, I am {free_user.name}, my age is {free_user.age} and my gender is {free_user.gender}",
            "s_name": free_user.name,
            "mimetype": "text"
        }, broadcast=False, to=current_user_sid)

        emit("join-user",{
            "status": "found"
        }, broadcast=False, to=free_user.sid)

        emit("status-message", {
                "message": "You're connected to a stranger!",
                "mimetype": "text"
            }, broadcast=False, to=free_user.sid)
        
        emit("new-message", {
            "data": f"Hello, I am {user.name}, my age is {user.age} and my gender is {user.gender}",
            "s_name": user.name,
            "mimetype": "text"
        }, broadcast=False, to=free_user.sid)


@socketio.on("disconnect")
def on_disconnect():
    current_user_sid = request.sid

    user = ChatUser.query.filter(ChatUser.sid == current_user_sid).first()
    if user is not None:
        db.session.delete(user)
        db.session.commit()

    if user is not None and user.status == "busy":
        message_to_sid = user.message_to
        message_to_user = ChatUser.query.filter(ChatUser.message_to == message_to_sid).first()

        if message_to_user is not None:
            message_to_user.delete(message_to_user)
            db.session.commit()
        
        if message_to_sid is not None:
            emit("status-message", {
                "message": "Stranger is disconnected!"
            }, broadcast=False, to=message_to_sid)

            emit("disconnect", {}, broadcast=False, to=message_to_sid)


@socketio.on("send-message")
def on_send_message(data:dict):
    current_user_sid = request.sid

    current_user = ChatUser.query.filter(ChatUser.sid == current_user_sid).first()
    
    if current_user is not None:
        message_to_user = ChatUser.query.filter(ChatUser.sid == current_user.message_to).first()

        if message_to_user is not None:
            message_to_sid = message_to_user.sid
    
            if data.get("data"):
                data.update({
                    "s_name": current_user.name
                })
                emit("new-message", data, broadcast=False, to=message_to_sid)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
</head>

<body>
    <div class="app-cover" style="position: static;">
        <div id="top-app" style="position: static;">
            <div action="#" class="btns m-v" id="top-btns">
                <a href="/" class="btn">{{app_name}}</a>
                <a href="{{url_for('Message.index')}}" class="btn">Message</a>
                <a href="{{url_for('Home.about')}}" class="btn">About</a>
                <a href="{{url_for('Home.terms')}}" class="btn">Terms</a>
            </div>
        </div>
    </div>
    <div class="container">
        {% block body %}{% endblock %}
    </div>
</body>

</html>

app/templates/home/about.html
{% extends "base.html" %}

{% block body %}
<h1>About</h1>
<div>
    <p>{{app_name}} is a free service to chat with anyone around the world without login or any other credentials.</p>
    <p>{{app_name}} is started so people around the world can communicate each other, it collects the name, age, gender and connects as your rules match.</p>
    <p>This is a free website, you don't have to pay for anything, and also it's safe your data is stored on your device as cookie format and used when you're request to connect with stranger.</p>
    <p>It's Anonymous service, we ask you name for easy conversation between you and stranger, use any name that you like in-order to chat.</p>
    <p>Your chat is not monitored, you're free from monitoring.</p>
    <p>This website uses cookies and other third-party ad providers in order to earn money.</p>
    <p>Make sure you read terms of use of this website before messaging.</p>
</div>
<div>
    <p>
        <strong>{{app_name}}</strong>
        <br>
        <span>Free and Anonymous.</span>
    </p>
</div>
{% endblock %}

app/templates/home/index.html
{% extends 'base.html' %}

{% block body %}
<h1 class="main-header">Chat with stranger</h1>
<form action="{{ url_for('Home.index') }}" method="post">
    <div><span style="font-size:22px; margin: 15px 0px;display: block; font-weight: bold;">Enter your details or leave it blank and start messaging</span></div>

    <div class="label">
        <label for="m-name">Your name</label>
        <input type="text" name="m-name" id="m-name" />
    </div>

    <div class="label">
        <label for="m-age">Your age</label>
        <select name="m-age" id="m-age">
            <option value="unknown">Select age</option>
            <option value="13-17">13 to 17</option>
            <option value="18-30">18 to 30</option>
            <option value="31-40">31 to 40</option>
            <option value="41-50">41 to 50</option>
            <option value="51+">51+</option>
        </select>
    </div>

    <div class="label">
        <label for="m-looking-age">Looking for age</label>
        <select name="m-looking-age" id="m-looking-age">
            <option value="unknown">Select age</option>
            <option value="13-17">13 to 17</option>
            <option value="18-30">18 to 30</option>
            <option value="31-40">31 to 40</option>
            <option value="41-50">41 to 50</option>
            <option value="51+">51+</option>
        </select>
    </div>

    <div class="label">
        <label for="m-gender">Your Gender</label>
        <select name="m-gender" id="m-gender">
            <option value="unknown">Select gender</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
        </select>
    </div>

    <div class="label">
        <label for="m-looking-gender">I'm looking for</label>
        <select name="m-looking-gender" id="m-looking-gender">
            <option value="unknown">Select gender</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
        </select>
    </div>

    <div class="label">
        <small>By clicking below button you agree to our terms of using service</small>
    </div>

    <input type="submit" value="Start messaging" class="norm-btn">
</form>
{% endblock %}

app/templates/home/terms.html
{% extends "base.html" %}

{% block body %}
<h1>Terms</h1>
<div>
    <p>{{app_name}} is a free anonymous chat service website.</p>
    <p>You're using this website to only chat with stranger, you're not monitored that does not mean you use abusive content in the chat.</p>
    <p>you don't have to pay anything to use service, it's free but {{app_name}} use third-party ad providers and traffic tools to monitor traffic and to earn money by showing some ads.</p>
    <p>Your data is safe, it's in your device only for a session. This data is saved when you're connected and when you disconnect your data is deleted.</p>
    <p>You must be a 13 year old before using {{app_name}} service.</p>
    <p>You must respect anyone on this website and anyone's data with you chat.</p>
    <p>By using {{app_name}} service, you give us permission to use the storage, store cookie and other third party libraries.</p>
    <p>{{app_name}} work constantly on improving terms of using this website and to improve this product, by updating you will have notification at Index page.</p>

    <p><b><em>Terms @ date: 12/02/2022</em></b></p>
</div>

{% endblock %}

app/templates/message/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    <title>Chat with stranger (without login)</title>
</head>
<body>
    <div class="app-cover">
        <div id="top-app">
            <form action="#" class="btns m-v" id="top-btns">
                <button id="connect-btn" type="button">Connect</button>
                <button id="disconnect-btn" type="button" disabled>Disonnect</button>
                <button id="dl-mode-btn" type="button">Dark/Light</button>
                <div class="btn" style="cursor: default;">
                    Live&nbsp;users&nbsp;:&nbsp;{{live_users_count}}
                </div>
                <a href="{{ url_for('Home.index') }}" class="btn">Back&nbsp;to&nbsp;Home</a>
            </form>
        </div>

        <div id="message-container" class="m-v">
            
        </div>

        <div id="app-bottom">
            <form action="#" id="message-form" >
                <textarea id="message-to-send" placeholder="Type your message here..." disabled autocomplete="off"></textarea>
                <input type="file" name="message-attach-file" id="message-attach-file" hidden disabled>
                <label class="btn" id="message-attach-btn" for="message-attach-file" style="display: flex; flex-direction: column; justify-content: center;align-items: center;">Attach</label>
                <input type="submit" id="message-send-btn" value="Send" disabled>
            </form>
        </div>
    </div>
    <script type="module" src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>